---
# tasks file for create_kvm_network

# Define a new network
- virt_net:
    command: define
    name: "{{ kvm_network_name }}"
    xml: '{{ lookup("template", "virt-net.xml.j2") }}'

# Start a network
- virt_net:
    command: create
    name: "{{ kvm_network_name }}"

# Ensure that a given network will be started at boot
- virt_net:
    autostart: yes
    name: "{{ kvm_network_name }}"


# Ensure that a given network will be started at boot
- virt_net:
    autostart: yes
    name: "{{ kvm_network_name }}"

