---
# tasks file for setup_openshift4

- name: Change file ownership, group and permissions
  file:
    path: /opt/ocp4
    state: directory




- name: Write out install-config file
  command : ssh-keygen -q -t rsa -b 4096  -f /opt/ocp4/ocp4_rsa -C noname -N ""
  args:
    creates: /opt/ocp4/ocp4_rsa


- name: slurp the pubkey for passing to other servers as authorized_key
  slurp:
    src: /opt/ocp4/ocp4_rsa.pub
  register: new_rsa_key
  

- name: Write out install-config file
  template:
    src: "{{ role_path }}/templates/install-config.yaml.j2"
    dest: /opt/ocp4/install-config.yaml

- name: copy install-config.yaml file for forensic
  copy:
    src: /opt/ocp4/install-config.yaml
    dest: /opt/ocp4/install-config.yaml.bak
    remote_src: yes


- name: Run openshift-install command
  command: chdir=/opt/ocp4 openshift-install create ignition-configs --dir=/opt/ocp4


- name: copy the ignition files to http server location
  copy:
    src: /opt/ocp4/{{item}} 
    dest: /var/www/html/ignition/
    remote_src: yes
  with_items: 
    ['master.ign', 'bootstrap.ign', 'worker.ign']

- name: restocon command on http server
  command: restorecon -vR /var/www/html/
